/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthDialog: typeof import('./src/components/auth-dialog/index.vue')['default']
    Child: typeof import('./src/components/child.vue')['default']
    CircleMenu: typeof import('./src/components/circle-menu/index.vue')['default']
    Parent: typeof import('./src/components/parent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarUpload: typeof import('@varlet/ui')['_UploadComponent']
    VarUploader: typeof import('@varlet/ui')['_UploaderComponent']
  }
}
