/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/child.vue')['default']
    CircleMenu: typeof import('./src/components/circle-menu/index.vue')['default']
    Parent: typeof import('./src/components/parent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
